### ISSUE TITLE
Remaining sidecar debugging issues

### ISSUE THREAD

**Issue by justinwilaby** [microsoft/BotFramework-Emulator#1443]
Remaining Sidecar debugging issues:

**P0's**
- [x] Label color contrast issues
- [x] Bot State selected color contrast issues
- [x] Graph/Json tab focus indication
- [x] Switching to sidecar mode after failing to open a bot file produces a blank screen
- [x] Slider on edge of webchat can get stuck unless you pull it waaaay over to the right side of the app. (tony) #1460
- [x] Toggling back to Emulator mode from Sidecar has zero UI indication of the mode switch
- [x] "Diff with previous" appears to only utilize the most recent bot state
- [x] Bot State element revisions (Justin) #1458
        Colors: (theme-specific)
          - Non-selected bot states should be grey
          - Selected Bot State should be white
          - On hover of any Bot State should be white
          - In diff mode, the "previous" diffed bot state font should be grey
          - In diff mode, the previous bot state indicator should be red, not blue
- [x] Default to the JSON view instead of the graph view, re-order the tabs in the extension pane (Tony) #1457 
- [x] Welcome Page changes (Chris) #1461
       When in sidecar mode, change the following:
            1. Remove the My Bots box
            2. Remove the "Sign in with Azure controls"
            3. Remove the "create a new bot configuration" text + link
            5. Change Heading copy to say: 

    Bot Framework Emulator
    Bot Inspector <working title>
    Version 4 (BETA)

- [x] Documentation (Justin) #1463 
        - Add a link that on the Welcome page in Sidecar mode that opens the Sidecar Debugging Doc
        - Add a Sidecar Debugging Doc as a tabbed document (Copy incoming) (Justin)
        - Add a Sidecar link in the Help menu that when clicked opens the Sidecar debugging doc in a new tab

When SDK bits are ready:
- [x] Infrastructure changes (Justin) #1465 
       - Remove starting a restify server on a fixed port (9000) when entering Sidecar mode
       - Cleanup additional logic pertaining to this server:port

- [x] Bot Connections (Tony)
        - Connect to a bot in Sidecar mode via url
        - Issue `/INSPECT open` command to bot when connection initiate

- [x] Token storage/rendering (Justin)
        - Receive `/INSPECT connect <guid>` command on response of /DEBUG open command and store it somewhere 
        - Render `/INSPECT connect <token>` command as an Activity in the WebChat control as the first interactable element in the conversation tab. When clicked, the JSON pane exposes the command

- [x] Bot State context menu breaks (Justin) #1500 
       - After right clicking on "Bot State" and selecting "copy text", right clicking on "Bot State" no longer brings up dropdown menu

- [x] Opening any .bot file in Emulator mode prompts switching debug modes and closes all tabs (Justin) #1501
       - This occurs when toggling between .bot files in Emulator mode, or opening your very first .bot file without any .bot files open. 

- [x] Address inspector-preload path in slightly better way (Tony)
      - One option: Add a new field to the `clientAwareSettings` state on load to referencing this special path to the preload file.

- [x] Hide Graph viz altogether for Beta (Chris)
      - The feedback has been overwhelming. We saw large state trees in the Bug Bash and it was less comprehensible than looking at the raw JSON. We will revisit after \\BUILD.

- [x] CHANNELS.md updates (Chris)
     - Adjust middleware example to include parameters passed in to the middleware
     - Adjust parts about _deployment_ to azure, bot _channel registration_ on the portal is enough using ngrok and localhost.

**P1's**
- [x]  Save urls supplied when connecting to a bot via url in a MRU structure. Exposed as dropdown list/autocomplete as users are inputting url characters like the html5 `datalist`. (Tony)
