### ISSUE TITLE
4.5 Release Checklist

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1532]
### .bot files
- [ ] create a new .bot file with keys encrypted
- [ ] edit existing .bot file providing secret to decrypt keys for .bot file not created by the Emulator
- [ ] load a .bot file to start conversation

### starting conversations
- [ ] start conversation via .bot file
- [ ] start conversation via url
- [ ] restart .bot file conversation (same user id, new user id, overridden user id)
- [ ] restart url conversation (same user id, new user id, overridden user id)

### chat control
- [ ] rendered activity types are clickable and load in the inspector

### log panel
- [ ] see appropriate status codes (200, 201, 401, 400, etc)
- [ ] all clickable elements load appropriate inspectors (Message, protocol events, LUIS traces, etc)

### inspectors
- [ ] LUIS train/publish via a LUIS trace

### bot inspector
- [ ] rendered activity types are clickable and load in the inspector (message, bot state)
- [ ] log items render appropriately and are clickable

### transcripts
- [ ] emulator mode save
~~- [ ] inspector mode save~~ removed until we can distinguish between regular & inspector transcripts
- [ ] load into conversation in transcript mode

### service connections
- [ ] log in to Azure
- [ ] navigate discovered resources/subscriptions
- [ ] add LUIS/QnA/Dispatch services to .bot file
- [ ] add new service manually

### samples
- [ ] core-bot
- [ ] welcome users
- [ ] bot authentication
- [ ] nlp-with-dispatch
- [ ] qnamaker

### protocols/schemes
- [ ] using `bfemulator://` can start the emulator with the appropriate context

### platforms
- [ ] macOS
- [ ] Windows
- [ ] Linux 

### auto-update
- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by corinagum** [comment]
Checking for an update on 4.4.1-59264 (must be in administrator mode) enables Restart to auto update, which updates to 4.4.1. Is this behavior we want?

**Comment by tonyanziano** [comment]
@corinagum If you don't have the "Use pre-release versions" checkbox checked in Settings, then yes, it is expected to update to the latest stable release. The new patch, 4.4.2, will not require admin privileges though.

**Comment by tonyanziano** [comment]
Signing off for:

- [X] Windows
- [X] Linux

**Comment by tonyanziano** [comment]
4.5 is live!

https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.5.0

**Comment by tonyanziano** [comment]
To add to checklist for next release:

Ensure that adaptive cards function properly (clicking within input fields focuses, postbacks are sent, etc.)
