### ISSUE TITLE
[4.6 Tracking] Implement HTML App Menu

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Emulator#1876]
Addresses the following accessibility issues:

#1802, #1803, #1804 

Work to be completed:

- [X] Disable native menu for Windows
- [x] Implement menu widget
- [x] Implement app menu component (File, Debug, Edit, etc.) that hooks into and uses menu widget
- [x] A11y
- [x] Wire up menu functionality / state
- [x] Theming / styling
- [x] Polish
- [x] Tests

**Comment by tonyanziano** [comment]
Addressed in #1893
