### ISSUE TITLE
4.6 Release checklist

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Emulator#1942]
### .bot files
- [x] create a new .bot file with keys encrypted
- [x] edit existing .bot file providing secret to decrypt keys for .bot file not created by the Emulator
- [x] load a .bot file to start conversation

### starting conversations
- [x] start conversation via .bot file
- [x] start conversation via url
- [x] restart .bot file conversation (same user id, new user id, overridden user id)
- [x] restart url conversation (same user id, new user id, overridden user id)

### chat control
- [x] rendered activity types are clickable and load in the inspector

### log panel
- [x] see appropriate status codes (200, 201, 401, 400, etc)
- [x] all clickable elements load appropriate inspectors (Message, protocol events, LUIS traces, etc)

### inspectors
- [x] LUIS train/publish via a LUIS trace

### bot inspector
- [x] rendered activity types are clickable and load in the inspector (message, bot state)
- [x] log items render appropriately and are clickable

### transcripts
- [x] emulator mode save
~~- [ ] inspector mode save~~ removed until we can distinguish between regular & inspector transcripts
- [x] load into conversation in transcript mode

### service connections
- [x] log in to Azure
- [x] navigate discovered resources/subscriptions
- [x] add LUIS/QnA/Dispatch services to .bot file
- [x] add new service manually

### samples
- [x] core-bot
- [x] welcome users
- [x] bot authentication
- [x] nlp-with-dispatch
- [x] qnamaker

### protocols/schemes
- [x] using `bfemulator://` can start the emulator with the appropriate context

### .bot files
- [x] create a new .bot file with keys encrypted
- [x] edit existing .bot file providing secret to decrypt keys for .bot file not created by the Emulator
- [x] load a .bot file to start conversation

### starting conversations
- [x] start conversation via .bot file
- [x] start conversation via url
- [x] restart .bot file conversation (same user id, new user id, overridden user id)
- [x] restart url conversation (same user id, new user id, overridden user id)

### chat control
- [x] rendered activity types are clickable and load in the inspector

### log panel
- [x] see appropriate status codes (200, 201, 401, 400, etc)
- [x] all clickable elements load appropriate inspectors (Message, protocol events, LUIS traces, etc)

### inspectors
- [x] LUIS train/publish via a LUIS trace

### bot inspector
- [x] rendered activity types are clickable and load in the inspector (message, bot state)
- [x] log items render appropriately and are clickable

### transcripts
- [x] emulator mode save
~~- [ ] inspector mode save~~ removed until we can distinguish between regular & inspector transcripts
- [x] load into conversation in transcript mode

### service connections
- [x] log in to Azure
- [x] navigate discovered resources/subscriptions
- [x] add LUIS/QnA/Dispatch services to .bot file
- [x] add new service manually

### samples
- [x] core-bot
- [x] welcome users
- [x] bot authentication
- [x] nlp-with-dispatch
- [x] qnamaker

### protocols/schemes
- [x] using `bfemulator://` can start the emulator with the appropriate context

### .bot files
- [x] create a new .bot file with keys encrypted
- [x] edit existing .bot file providing secret to decrypt keys for .bot file not created by the Emulator
- [x] load a .bot file to start conversation

### starting conversations
- [x] start conversation via .bot file
- [x] start conversation via url
- [x] restart .bot file conversation (same user id, new user id, overridden user id)
- [x] restart url conversation (same user id, new user id, overridden user id)

### chat control
- [x] rendered activity types are clickable and load in the inspector

### log panel
- [x] see appropriate status codes (200, 201, 401, 400, etc)
- [x] all clickable elements load appropriate inspectors (Message, protocol events, LUIS traces, etc)

### inspectors
- [x] LUIS train/publish via a LUIS trace

### bot inspector
- [x] rendered activity types are clickable and load in the inspector (message, bot state)
- [x] log items render appropriately and are clickable

### transcripts
- [x] emulator mode save
~~- [ ] inspector mode save~~ removed until we can distinguish between regular & inspector transcripts
- [x] load into conversation in transcript mode

### service connections
- [x] log in to Azure
- [x] navigate discovered resources/subscriptions
- [x] add LUIS/QnA/Dispatch services to .bot file
- [x] add new service manually

### samples
- [x] core-bot
- [x] welcome users
- [x] bot authentication
- [x] nlp-with-dispatch
- [x] qnamaker

### protocols/schemes
- [x] using `bfemulator://` can start the emulator with the appropriate context

### auto-update
- [x] macOS
- [x] Windows
- [x] Linux

**Comment by tonyanziano** [comment]
Signing off on Windows & Linux. 👍
